"""User-supplied DAL2 experimental reference; coordinates are transcript-local."""
REFERENCE = (
    'ATGCTATAAAGGAATGGAAGTGCATTTTGCTATGATATGGGGAAATTATGAAGCCGATCAAACAATTAATTGTATCTAATCGGTCTCTTCTTTAGAAAA'
    'ATGAAGTTTTTTAGTTTGGCAGATGAGGCAGAATTTAAGTCAATAATCATTTCAAAAAACAAAGCAGTAG'
    'ATGTTATAGGATCTAAGTTAGGTGGTCAAGTGGTTTCTTTTTCAGATGAATGGTTTGCTTCTGCTGAAAATTTAATTCAGCCAACTGCTCCTATAAGGGATCCTACCAGATTTGTTCATTCAGGCGCATGGTACGACGGCTGGGAAACACGAAGACATAATGAGATGGAATACGATTGGGTTATCATCAAGATGGGAGTCGCTGCTGCCCATATTATTGGTGGTGAAATTGACACTGCGTTTTTCAATGGTAATCATGCACCATTTGTATCAATAGAGGCGCTCTATGACGAGGGCGAAGAAGGTAATATAGTGGAAGATGACTCGCGTTGGGTTGAGATTGTTGAGAAATTTGAGTGTGGTCCTTCGCAAAGGCATCTTTTCGTTAGAGGCAACGGCCTTACTAAAGAAAGGTTTACTC'
)
FORWARD_PRIMER = 'CATTGCAAGCAGTGGTATCAAC'
TSO = 'GCTAATCATTGCAAGCAGTGGTATCAACGCAGAGTACATGGG'
TSO_TAIL = 'GCAGAGTACATGGG'
REVERSE_PRIMER = 'GAGTAAACCTTTCTTTAGTAAGGCCG'
ANNOTATIONS = [dict(label=f'uORF{i} ATG', start=start, end=start+2, kind='start')
               for i,start in enumerate([1,14,32,37,48],1)] + [
    dict(label='Main DAL2 ATG',start=100,end=102,kind='start'),
    dict(label='Internal ATG A',start=122,end=124,kind='start'),
    dict(label='Internal ATG B',start=170,end=172,kind='start'),
    dict(label='Reverse-primer site',start=564,end=589,kind='primer')]
